# Generated by Django 5.2.4 on 2025-07-28 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('photos', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('location_type', models.CharField(choices=[('T', 'Tourist Site'), ('R', 'Restaurant'), ('H', 'Hotel'), ('C', 'Cafe'), ('S', 'Shop')], max_length=1)),
                ('description', models.TextField()),
                ('monday_open_hour', models.TimeField()),
                ('monday_close_hour', models.TimeField()),
                ('tuesday_open_hour', models.TimeField()),
                ('tuesday_close_hour', models.TimeField()),
                ('wednesday_open_hour', models.TimeField()),
                ('wednesday_close_hour', models.TimeField()),
                ('thursday_open_hour', models.TimeField()),
                ('thursday_close_hour', models.TimeField()),
                ('friday_open_hour', models.TimeField()),
                ('friday_close_hour', models.TimeField()),
                ('saturday_open_hour', models.TimeField()),
                ('saturday_close_hour', models.TimeField()),
                ('sunday_open_hour', models.TimeField()),
                ('sunday_close_hour', models.TimeField()),
            ],
        ),
    ]
