# Generated by Django 5.2.4 on 2025-07-28 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='friday_close_hour',
        ),
        migrations.RemoveField(
            model_name='location',
            name='friday_open_hour',
        ),
        migrations.RemoveField(
            model_name='location',
            name='monday_close_hour',
        ),
        migrations.RemoveField(
            model_name='location',
            name='monday_open_hour',
        ),
        migrations.RemoveField(
            model_name='location',
            name='saturday_close_hour',
        ),
        migrations.RemoveField(
            model_name='location',
            name='saturday_open_hour',
        ),
        migrations.RemoveField(
            model_name='location',
            name='sunday_close_hour',
        ),
        migrations.RemoveField(
            model_name='location',
            name='sunday_open_hour',
        ),
        migrations.RemoveField(
            model_name='location',
            name='thursday_close_hour',
        ),
        migrations.RemoveField(
            model_name='location',
            name='thursday_open_hour',
        ),
        migrations.RemoveField(
            model_name='location',
            name='tuesday_close_hour',
        ),
        migrations.RemoveField(
            model_name='location',
            name='tuesday_open_hour',
        ),
        migrations.RemoveField(
            model_name='location',
            name='wednesday_close_hour',
        ),
        migrations.RemoveField(
            model_name='location',
            name='wednesday_open_hour',
        ),
        migrations.AlterField(
            model_name='location',
            name='address',
            field=models.TextField(),
        ),
        migrations.CreateModel(
            name='OpeningHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('1', 'Monday'), ('2', 'Tuesday'), ('3', 'Wednesday'), ('4', 'Thursday'), ('5', 'Friday'), ('6', 'Saturday'), ('7', 'Sunday')])),
                ('open_time', models.TimeField()),
                ('close_time', models.TimeField()),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opening_hours', to='location.location')),
            ],
        ),
    ]
