# Generated by Django 5.2.4 on 2025-07-30 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0002_remove_location_friday_close_hour_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='helper_description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='phone',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
