# Generated by Django 5.2.4 on 2025-07-30 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0004_remove_location_photos_photos'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Photos',
            new_name='Photo',
        ),
    ]
