# Generated by Django 5.2.4 on 2025-07-30 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0005_rename_photos_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='always_open',
            field=models.BooleanField(default=False),
        ),
    ]
