# Generated by Django 5.2.4 on 2025-07-31 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0006_location_always_open'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='name',
            new_name='title',
        ),
        migrations.AlterField(
            model_name='location',
            name='location_type',
            field=models.CharField(choices=[('N', 'Nature'), ('T', 'Tourist Site'), ('HH', 'Historical'), ('R', 'Restaurant'), ('H', 'Hotel'), ('C', 'Cafe'), ('S', 'Shop'), ('PA', 'Park')], max_length=2),
        ),
    ]
