# Generated by Django 5.2.4 on 2025-07-31 09:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0008_alter_location_address_alter_location_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='openinghours',
            name='location',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='opening_hours', to='location.location'),
            preserve_default=False,
        ),
    ]
