# Generated by Django 5.2.4 on 2025-09-15 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0009_alter_openinghours_location'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='location',
            index=models.Index(fields=['lat', 'lon'], name='locations_lat_lon_idx'),
        ),
        migrations.AddIndex(
            model_name='location',
            index=models.Index(fields=['lat'], name='locations_lat_idx'),
        ),
        migrations.AddIndex(
            model_name='location',
            index=models.Index(fields=['lon'], name='locations_lon_idx'),
        ),
    ]
